### ISSUE TITLE
Clickable Nodes w/ JSONTree Enhancement

### ISSUE THREAD

**Issue by darekrossman** [romseguy/redux-devtools-chart-monitor#1]
I'm hooking into the TreeChart's `onClickText` prop and using JSONTree to render my object to the right....(using your [ChartMonitor](https://github.com/gaearon/redux-devtools/pull/123) in a seperate window).

Might be interesting to incorporate something like this as it sort of becomes a standalone dev tool (I've been using this on it's own all day and not even rendering the normal LogMonitor). Though hooking into the LogMonitor would probably be even cooler : )

![statetree](https://cloud.githubusercontent.com/assets/1527110/10009109/e28f4862-60a5-11e5-9520-9e27f246f2d0.gif)

Anyhow, thanks for this!

**Comment by romseguy** [comment]
See [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension).
