### ISSUE TITLE
ChartMonitor doesn't work because monitorState is undefined

### ISSUE THREAD

**Issue by hronro** [romseguy/redux-devtools-chart-monitor#11]
![2016-06-26 11 39 28](https://cloud.githubusercontent.com/assets/15059605/16360393/e8a06c86-3b92-11e6-8fec-054a3acdc3a4.png)

I used `DockMonitor` to make it dockable.

``` javascript
const DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='ctrl-h'
               changePositionKey='ctrl-q'
               changeMonitorKey='ctrl-m'
               defaultIsVisible={ false }>
    <LogMonitor />
    <SliderMonitor />
    <DiffMonitor />
    <ChartMonitor />
  </DockMonitor>
);
```

My DockMonitor version is 1.1.1, ChartMonitor version is 1.4.1.
So how to fix it?

**Comment by romseguy** [comment]
Certainly a problem with your setup, check out https://github.com/zalmoxisus/redux-devtools-extension

**Comment by hronro** [comment]
@romseguy No, I don't use the chrome extension, I just use [DockMonitor](https://github.com/gaearon/redux-devtools-dock-monitor), and all other moniotor like [LogMonitor](https://github.com/gaearon/redux-devtools-log-monitor) and [DiffMonitor](https://github.com/whetstone/redux-devtools-diff-monitor) works fine.
