### ISSUE TITLE
D3-related issues when using with the latest deps (__oldData__)

### ISSUE THREAD

**Issue by kachkaev** [romseguy/redux-devtools-chart-monitor#16]
Hi Romain,

I added `redux-devtools-chart-monitor` to a new project recently and noticed some rendering issues, which I did not see before. Here's the summary:

![issue with latest deps](https://cloud.githubusercontent.com/assets/608862/20568594/ebddcc72-b194-11e6-9b15-15b9b264e167.PNG)

(`VM6084:208 Uncaught TypeError: Cannot read property '__oldData__' of undefined` appears on first render and each time I click on a node)

To make sure it's not something about my project, I replicated the issue in your `redux-store-visualizer` demo after updating all deps (see https://github.com/romseguy/redux-store-visualizer/pull/4). It's still unclear to me how to fix it, so I'm submitting an issue instead of a PR. Missing edges between the nodes might give a clue.

**Comment by romseguy** [comment]
Fixed with https://github.com/romseguy/d3-state-visualizer/pull/11

**Comment by kachkaev** [comment]
All works after updating to 1.6.1! Thanks @romseguy!
